### ISSUE TITLE
json location error

### ISSUE THREAD

**Issue by Jrebort** [bjj9/EVE_SCPT#2]
I want to use your model, but have some problem.
I put `eye_net_without_pupil.pt` in `./src/models/trained_model_params/`
But, run` python ./eval_codalab_offline.py` in ./src. Have following infomation:

```
Traceback (most recent call last):
  File "./eval_codalab_offline.py", line 5, in <module>
    eval_codalab_basic(output_suffix='online', skip_first_round_if_memory_is_ready=True) 
  File "/home/xxx/EVE_SCPT/src/eval_codalab_basic.py", line 65, in eval_codalab_basic
    model = EVEC(output_predictions=True, online_refinement_starts_from=online_refinement_starts_from).to
(device)
  File "/home/xxx/EVE_SCPT/src/models/evec.py", line 93, in __init__
    state_dict = torch.load(config.eye_net_load_from_specified_location, map_location=device)
  File "/home/xxx/.conda/envs/EVE/lib/python3.6/site-packages/torch/serialization.py", line 584, i
n load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/xxx/.conda/envs/EVE/lib/python3.6/site-packages/torch/serialization.py", line 234, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/xxx/.conda/envs/EVE/lib/python3.6/site-packages/torch/serialization.py", line 215, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/samba/room/codespace/pythonWorkingSpace/EVE_SCPT/src/models/trained_model_params/eye_net_without_pupil.pt'
```

Can you tell me the method to fix the error.

**Comment by Jrebort** [comment]
The issue is solved.
